version: 2.1
# Use a package of configuration called an orb.
orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  # Exercise - Rollback
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable
          # ${CIRCLE_WORKFLOW_ID:0:5} takes the first 5 chars of the variable CIRCLE_CI_WORKFLOW_ID
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}

jobs:
  # Exercise: Infrastructure Creation
  # Exercise - Rollback
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy --template-file infrastructure/servers.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1
      # Fail the job intentionally to simulate an error.
      # Uncomment the line below if you want to fail the current step
      # - run: return 1
      - destroy_environment

  listEC2IPs:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: Create Cloudformation Stack
          command: |
            echo [all] > ~/inventory.txt && aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --output text >> ~/inventory.txt
      - run:
          name: Display the inventory.txt value for test purpose
          command: cat ~/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory.txt

  # Exercise: Config and Deployment
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ['64:32:93:db:6a:cd:94:20:f5:68:1f:fc:9e:15:d1:cc'] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install Ansible
          command: |
            # install the dependencies needed for your playbook
            apk add --update ansible
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Display the inventory.txt value for test purpose
          command: cat ~/workspace/inventory.txt
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i ~/workspace/inventory.txt ansible/playbook.yml

  # Exercise: Smoke Testing
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Display the inventory.txt value for test purpose
          command: grep -m 2 -o '.*' ~/workspace/inventory.txt | tail -n 1
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            grep -m 2 -o '.*' ~/workspace/inventory.txt | tail -n 1 | while read p; 
            do
              if curl -s --head "$p"
              then
                echo "Pass the smoke testing"
              else
                return 1
              fi
            done

      - destroy_environment

workflows:
  deploying:
    jobs:
      # - create_infrastructure
      # - listEC2IPs:
      #     requires:
      #       - create_infrastructure
      # - configure_infrastructure:
      #     requires:
      #       - listEC2IPs
      # - smoke_test:
      #     requires:
      #       - configure_infrastructure
      - listEC2IPs
      - smoke_test:
          requires:
            - listEC2IPs
